[build]
  publish = "dist"
  command = "npm run build"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/found_with_me/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
